version: "3.8"

services:
  mongodb:
    image: "mongo:6"
    container_name: mongo
    ports:
      - "5010:27017" # For access from host machine
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Not required
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_listener", "5672"]
      interval: 10s
      timeout: 10s
      retries: 5

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - 5000:5000
    depends_on:
      - mongodb

  task-service:
    build: ./task-service
    container_name: task-service
    ports:
      - 5001:5001
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started

  notification-service:
    build: ./notification-service
    container_name: notification-service
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  mongo_data:
